### ISSUE TITLE
[Dúvida]: Possível texto escrito em um lugar que não deveria. 😜

### ISSUE THREAD

**Issue by gabrielduete** [RaayaneGomes97/RaayaneGomes97#1]
#### O nome ''python'' deveria estar ali no começo do readme logo em cima do header mesmo?

![image](https://github.com/RayaneGomes97/RayaneGomes97/assets/59345698/cd42bc73-5ac7-4f0e-9c1d-4a4812290658)

**Comment by RayaneGomes97** [comment]
Não mesmo, obrigada pela observação, KKKKKKKKKKKKKKKK
